In [6]:
import numpy as np
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [49]:
b=np.array([[5,6,7,8],[9,10,11,12]])
b


array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
b.shape=(3,4)
b

ValueError: cannot reshape array of size 8 into shape (3,4)

In [28]:
f=np.array([1,2,3,4,5,6,7,8,9,10])
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
f.shape=(5,2)
f

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [31]:
f.shape=(2,5)
f

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [41]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [51]:
?g.shape

In [52]:
g.shape?

In [53]:
h=np.random.randint(10,size=5)
h

array([3, 7, 4, 8, 2])

In [57]:
g=np.random.randint(55,size=10)
g

array([35, 42, 49, 19, 34, 40, 16, 34,  2,  4])

In [58]:
g[0]

35

In [59]:
g[-1]

4

In [60]:
g[5]

40

In [61]:
g>10

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False])

In [62]:
g<30

array([False, False, False,  True, False, False,  True, False,  True,
        True])

In [63]:
g*2

array([70, 84, 98, 38, 68, 80, 32, 68,  4,  8])

In [66]:
g/2

array([17.5, 21. , 24.5,  9.5, 17. , 20. ,  8. , 17. ,  1. ,  2. ])

In [67]:
g[0:3]

array([35, 42, 49])

In [68]:
g*g

array([1225, 1764, 2401,  361, 1156, 1600,  256, 1156,    4,   16])

In [52]:
import numpy as np
a=np.zeros(3)
a

array([0., 0., 0.])

In [70]:
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [71]:
type(a)

numpy.ndarray

In [72]:
type(a[0])

numpy.float64

In [5]:
import numpy as np
y=np.array([5,6,3,5,3,2])
y

array([5, 6, 3, 5, 3, 2])

In [6]:
y@y

108

In [7]:
a=np.array([5,9,3,4])
a

array([5, 9, 3, 4])

In [8]:
a.cumsum()

array([ 5, 14, 17, 21], dtype=int32)

In [9]:
a.cumprod()

array([  5,  45, 135, 540], dtype=int32)

In [10]:
a.sum()

21

In [12]:
b=a>5
b

array([False,  True, False, False])

In [21]:
v=np.array([5,4,3,24,55,9])
v

array([ 5,  4,  3, 24, 55,  9])

In [22]:
v<5

array([False,  True,  True, False, False, False])

In [19]:
v.any()

True

In [20]:
v.all()

True

In [24]:
v.sort()
v

array([ 3,  4,  5,  9, 24, 55])

In [27]:
x=np.array([3,2,5,5,7,8,7,7,0,55,5,5])
x

array([ 3,  2,  5,  5,  7,  8,  7,  7,  0, 55,  5,  5])

In [32]:
c=np.unique(x)
c

array([ 0,  2,  3,  5,  7,  8, 55])

In [53]:
a=np.array([1,2,3,4,5,6,7,8])
b=np.array([5,4,3,6,2,8,6,7])

In [54]:
np.where(a>b,a,b)


array([5, 4, 3, 6, 5, 8, 7, 8])

In [57]:
result=np.array([55,44,32,11,67])


In [58]:
np.where(result>40,"pass","fail")

array(['pass', 'pass', 'fail', 'fail', 'pass'], dtype='<U4')

In [16]:
import numpy as np
f=np.array([5,3,5,66,3,5,4,6,2])
f

array([ 5,  3,  5, 66,  3,  5,  4,  6,  2])

In [17]:
f.ndim

1

In [18]:
f.size

9

In [19]:
f.shape

(9,)

In [29]:
import numpy as np
a=np.array([[1,2,3,4,5],[4,5,6,7],[88,9,6,5]])
a

array([list([1, 2, 3, 4, 5]), list([4, 5, 6, 7]), list([88, 9, 6, 5])],
      dtype=object)

In [30]:
a.ndim

1

In [31]:
a.size

3

In [32]:
a.shape

(3,)

In [34]:
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
b=np.arange(55).reshape(11,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54]])

In [46]:
import numpy as np
h=np.arange (4,77)
h

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
       55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75, 76])

In [47]:
h.ndim

1

In [48]:
h.size

73

In [16]:
import numpy as np
a=["asil","basil","faisal"]
b=["tariq","shah","bilal"]

In [17]:
a

['asil', 'basil', 'faisal']

In [18]:
b

['tariq', 'shah', 'bilal']

In [19]:
np.save("sub1.npy",a)

In [20]:
l1=np.load("sub1.npy")
l1

array(['asil', 'basil', 'faisal'], dtype='<U6')

In [22]:
np.savez("sub2",a=a,b=b)
l2=np.load("sub2.npz")
l2

In [23]:
a

['asil', 'basil', 'faisal']

In [24]:
b

['tariq', 'shah', 'bilal']

In [25]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [26]:
np.dot(x,y)

32

In [2]:
import numpy as np
a=np.array([1,2,3,4,5,6,8])
a

array([1, 2, 3, 4, 5, 6, 8])

In [4]:
a.max()

8

In [5]:
a.min()

1

In [6]:
a.sum()

29

In [8]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [10]:
b.sum(axis=1)

array([ 6, 22, 38])

In [32]:
import numpy as np
t=np.arange(1000)
t

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [33]:
t[2:6]

array([2, 3, 4, 5])

In [34]:
t[0:6:2]=1000

In [36]:
t[::-1]

array([ 999,  998,  997,  996,  995,  994,  993,  992,  991,  990,  989,
        988,  987,  986,  985,  984,  983,  982,  981,  980,  979,  978,
        977,  976,  975,  974,  973,  972,  971,  970,  969,  968,  967,
        966,  965,  964,  963,  962,  961,  960,  959,  958,  957,  956,
        955,  954,  953,  952,  951,  950,  949,  948,  947,  946,  945,
        944,  943,  942,  941,  940,  939,  938,  937,  936,  935,  934,
        933,  932,  931,  930,  929,  928,  927,  926,  925,  924,  923,
        922,  921,  920,  919,  918,  917,  916,  915,  914,  913,  912,
        911,  910,  909,  908,  907,  906,  905,  904,  903,  902,  901,
        900,  899,  898,  897,  896,  895,  894,  893,  892,  891,  890,
        889,  888,  887,  886,  885,  884,  883,  882,  881,  880,  879,
        878,  877,  876,  875,  874,  873,  872,  871,  870,  869,  868,
        867,  866,  865,  864,  863,  862,  861,  860,  859,  858,  857,
        856,  855,  854,  853,  852,  851,  850,  8

In [22]:
import numpy as np
a=np.array(["bilal","asad","ali","yak"])

In [23]:
a

array(['bilal', 'asad', 'ali', 'yak'], dtype='<U5')

In [24]:
a=="yak"

array([False, False, False,  True])

In [25]:
a[a=="yak"]

array(['yak'], dtype='<U5')

In [26]:
a[a=='man']

array([], dtype='<U5')

In [18]:
import numpy as np
c=np.array([3,4,6,7,8,9])
c

array([3, 4, 6, 7, 8, 9])

In [19]:
c<7


array([ True,  True,  True, False, False, False])

In [20]:
c[c<7]

array([3, 4, 6])

In [35]:
t=np.array([4,2,44,78,99])
t

array([ 4,  2, 44, 78, 99])

In [36]:
t[3]

78

In [37]:
t[t>78]

array([99])